### ISSUE TITLE
Todo/Request

### ISSUE THREAD

**Issue by xiandong79** [danielliwd/binance_rs_test#1]
- [ ] 非异步, 基于 binance-rs
  - [x] 行情、下单
  - [ ] ws 行情、下单、处理 respnese
- [ ] 异步, 基于 binance-rs-async
  - [x] 行情、下单
  - [ ] ws 行情、下单、处理 respnese
  - [ ] 补充 margin api 进入 binance-rs-async
- [ ] 策略
  - [ ] 学习 https://github.com/matrix-tang/ex-rs
    - 这里的 mysql/redis/helpers 组件 和项目 组织模式很棒
  - [ ] 学习 https://github.com/matrix-tang/Futures-Spot-Arbitrage-Binance-V1
    - 优点
      - 提供了优质的组件、策略结构 
    - 缺点
      - 项目没有使用 Margin API + 统一保证金账户，因此还需要划转资金，增加了复杂度。
      - 价差存进 mysql 作为一个策略，再读出来，时效性已经很差
      - 不能在策略执行过程中去 `// 插入详情表`， 延误了策略速度
      - [ ] 新建立一个 private 项目，补强此项目
    - 其他/疑问
      - 未来是应该有一个 strategies folder, 然后 期限套利是 其中一个策略。要准备好项目组织结构
      - 进行实际执行和分流的 func 是 event_start
      - redis 的作用 和必要性？ mysql 的必要性？ 价差存进 mysql 作为一个策略，再读出来，时效性已经很差
      - option_amount 是一个order size，还是 max position。应该有一个 持仓上限。 还是说 order size = max position, 最多只持有1个 order size？
      - 结论
         基于我们的顶级账户，直接把这个跑起来！优势很大！
  - [ ] 简单浏览(价值不高) rust 策略项目 https://github.com/mateusz-szczyrzyca/price-volatility-trading-bot 
    
   - 进一步需求
     - [ ] 订阅全市场 spot orderbook，future orderbook 供“期现套利”策略使用，是否要多进程（用mq 就行 不需要 shm /mmap）？单进程能否做到？
     - [ ] 模仿  aioquant 的标准化方式，在项目内 增加对 gateio交易所的 全部 REST websocket 的支持
       - 参考 [ccxt-rs](https://github.com/kizzx2/ccxt-rs/blob/1a665fc9f16a10f1723a0d4865fd28236d508387/rust/src/gateio.rs#L23)
     - [ ] 增加因子计算模块，其读取行情+计算因子，并推送给 xgboost 模型预测模块
     - [ ] xgboost 模型预测模块 计算 涨跌预测，推送给 策略模块

**Comment by lijiachang** [comment]
mark

**Comment by danielliwd** [comment]
https://github.com/danielliwd/binance_rs_async_test

**Comment by lijiachang** [comment]
https://github.com/matrix-tang/Futures-Spot-Arbitrage-Binance-V1

个人的一些看法，慢慢补充：

1. 账户模式应该优化：当前的双腿下单是先买现货->现货划转到合约->卖合约的步骤，应该改为类似于OKX多币种保证金模式，使用batch create order接口下单，在一个API中同时下两单
2. 多余的状态判断：单一条策略的处理流程中，每一步都要先进行MySQL查询，通过arb_strategy_ex的状态来推进策略的进行，这完全没有必要。
3. 平仓风险：当策略需要平仓的时候，合约平仓没有使用【reduce only】模式。
4. websocket连接不完善：没有处理交易所的ping/pong心跳； 还缺少了websocket断连重连机制。

**Comment by xiandong79** [comment]
“使用batch create order接口下单，在一个API中同时下两单”

这想法不对。一定是maker 开仓，另一侧 taker 对冲掉，更厉害的团队是 双maker，那么包含一些价格趋势预测。
要考虑手续费的cost  @lijiachang

**Comment by xiandong79** [comment]
在这个 更高级的项目中 
https://github.com/featherenvy/botvana

也有很多适合于 低延迟交易系统、行情系统的方案.

且 botnode/src/exchange/adapter.rs 能保证 统一的 interface （函数输入参数）可以适用到所有的交易所，是非常香的 adapter 或者 称作 wrapper

-------

不过，我觉得 这种分布式（Deployment architecture）的理念还是太复杂了。
适合我们当前的 junior 开发能力，还是直接 callback 函数吧， 类似 aioquant python版本。

**Comment by xiandong79** [comment]
https://github.com/crypto-crawler/crypto-crawler-rs

https://github.com/monomadic/cryptotrader-core

https://github.com/Nouzan/exc
The abstraction layer of exchanges.

https://github.com/kanekoshoyu/kucoin_arbitrage
期待 类似 aioquant 那种多交易所包装好的 统一接口的 项目

https://github.com/ybangaru/arbitrage_trading_rust_bot
这个套利资金费率

**Comment by lijiachang** [comment]
https://github.com/crypto-crawler/crypto-crawler-rs
说到adapter模式，这个项目做的非常好，上层不用关心交易所的实现，使用common trait（接口）抽象，来让各个交易所各自的实现

我的能力还不能理解他的写法，但是明白他抽象的能力

**Comment by lijiachang** [comment]
> https://github.com/Goodnessuc/cex-aggregator 是不是一个 很好的 统一的API interface
@xiandong79 这个项目文件是空的呀，是我打开的方式不对吗😂

**Comment by xiandong79** [comment]
> > https://github.com/Goodnessuc/cex-aggregator 是不是一个 很好的 统一的API interface
> > @xiandong79 这个项目文件是空的呀，是我打开的方式不对吗😂

那就忽略它。
